[Unit]
Requires=seatd.service
After=seatd.service

[Service]
Environment=XDG_SESSION_TYPE=wayland
Environment=LIBSEAT_BACKEND=seatd
ExecStart=
ExecStart=/usr/lib/custom-distro/check-user-session /usr/lib/custom-distro/check-desktop-session
